// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.28;

import {ProxyAdmin} from '@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol';
import {TransparentUpgradeableProxy} from '@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol';
import {Test} from 'forge-std/Test.sol';

import {DKIMRegistry} from '@zk-email/contracts/DKIMRegistry.sol';

import {SafetyNet} from 'src/contracts/SafetyNet.sol';
import {ZkEmailFluVerifier} from 'src/contracts/ZkEmailFluVerifier.sol';
import {FluClaimGroth16Verifier} from 'src/contracts/verifiers/FluClaimGroth16Verifier.sol';
import {ISafetyNet} from 'src/interfaces/ISafetyNet.sol';
import {IZkEmailFluVerifier} from 'src/interfaces/IZkEmailFluVerifier.sol';

import {FluClaimV2Fixture} from 'test/fixtures/FluClaimV2Fixture.sol';
import {MockERC20} from 'test/mocks/MockERC20.sol';

/// @dev End-to-end proof of the design-C flu-claim pipeline: a REAL two-email Groth16 proof,
///      generated by the compiled FluClaimV2 circuit over two DKIM-signed fixture emails
///      (circuits/scripts/gen-v2-fixture.mjs + prove-v2.sh), verified on-chain through the
///      snarkjs-generated verifier and the full ZkEmailFluVerifier + SafetyNet stack. This is the
///      contract-side validation that the deployed 6-signal layout, the dual DKIM checks, the
///      31-byte wallet packing, and the in-circuit To(A)==From(B) binding all agree with the circuit.
///
///      The DKIM keys are committed TEST keys; never register them on a production DKIMRegistry.
contract FluClaimV2ProofIntegration is Test {
  bytes32 internal _pubkeyHashA;
  bytes32 internal _pubkeyHashB;

  SafetyNet internal _sn;
  ZkEmailFluVerifier internal _verifier;
  DKIMRegistry internal _dkim;
  MockERC20 internal _token;

  address internal _owner = makeAddr('owner');
  // The claimant is fixed by the proof (its wallet is proven inside binding email B's subject)
  address internal _claimant = FluClaimV2Fixture.CLAIMANT;

  function setUp() public {
    _pubkeyHashA = FluClaimV2Fixture.PUBKEY_HASH_A;
    _pubkeyHashB = FluClaimV2Fixture.PUBKEY_HASH_B;

    address impl = address(new SafetyNet());
    address admin = address(new ProxyAdmin(_owner));
    _sn = SafetyNet(address(new TransparentUpgradeableProxy(impl, admin, abi.encodeWithSelector(SafetyNet.initialize.selector, _owner))));

    _dkim = new DKIMRegistry(_owner);
    address groth16 = address(new FluClaimGroth16Verifier());
    _verifier = new ZkEmailFluVerifier(_owner, address(_sn), groth16, address(_dkim));

    vm.startPrank(_owner);
    _dkim.setDKIMPublicKeyHash(FluClaimV2Fixture.PROVIDER_DOMAIN, _pubkeyHashA);
    _dkim.setDKIMPublicKeyHash(FluClaimV2Fixture.BINDING_DOMAIN, _pubkeyHashB);
    _verifier.setProvider(FluClaimV2Fixture.PROVIDER_DOMAIN, true);
    _verifier.setBindingProvider(FluClaimV2Fixture.BINDING_DOMAIN, true);
    _sn.setFluClaimVerifier(address(_verifier));
    vm.stopPrank();

    _token = new MockERC20('Mock', 'MOCK');
    _token.mint(_claimant, 1_000_000 ether);
    vm.prank(_claimant);
    _token.approve(address(_sn), type(uint256).max);
    vm.prank(_owner);
    _sn.setTokenAllowed(address(_token), true);
  }

  function _defaultNet(address _netOwner) internal view returns (ISafetyNet.SafetyNet memory _cfg) {
    _cfg = ISafetyNet.SafetyNet({
      id: 0,
      owner: _netOwner,
      minimumMembers: 2,
      maximumMembers: 5,
      contestThreshold: 33,
      safetyNetStart: 0,
      token: address(_token),
      members: new address[](0),
      initialDeposit: 100 ether,
      fixedDeposit: 10 ether,
      redeemRatio: 1,
      autoThreshold: 50 ether,
      contestWindow: 3 days,
      epochDuration: 30 days,
      smallWithdrawsLimit: 3
    });
  }

  function _encodedProof() internal pure returns (bytes memory) {
    return abi.encode(
      IZkEmailFluVerifier.FluClaimProof({
        providerDomain: FluClaimV2Fixture.PROVIDER_DOMAIN,
        bindingDomain: FluClaimV2Fixture.BINDING_DOMAIN,
        a: FluClaimV2Fixture.a(),
        b: FluClaimV2Fixture.b(),
        c: FluClaimV2Fixture.c(),
        signals: FluClaimV2Fixture.signals()
      })
    );
  }

  /// @dev create (keyed helper owner) → invite claimant → onboard both → advance one epoch → settle
  function _claimReadyNet() internal returns (uint256 id) {
    (address keyedOwner, uint256 ownerKey) = makeAddrAndKey('keyedOwner');
    ISafetyNet.SafetyNet memory cfg = _defaultNet(keyedOwner);
    _token.mint(keyedOwner, 1_000_000 ether);
    vm.prank(keyedOwner);
    _token.approve(address(_sn), type(uint256).max);

    id = _sn.create('Flu V2 Net', cfg);
    _redeemInvite(id, _claimant, ownerKey, 1);
    vm.prank(keyedOwner);
    _sn.start(id);
    vm.prank(keyedOwner);
    _sn.deposit(id, cfg.initialDeposit);
    vm.prank(_claimant);
    _sn.deposit(id, cfg.initialDeposit);
    vm.warp(_sn.getSafetyNet(id).safetyNetStart + cfg.epochDuration);
  }

  function test_RealTwoEmailProofSettlesFluClaim() public {
    uint256 id = _claimReadyNet();

    uint256 balanceBefore = _token.balanceOf(_claimant);
    uint256 expectedPayout =
      (_sn.safetyNetMemberContribute(id, _claimant) * _sn.getEffectiveRedeemRatio(id, _claimant) / 30) * _sn.FLU_PAYOUT_DAYS();

    // Settle the REAL two-email proof: dual DKIM + domain allowlists + wallet binding + nullifier
    vm.prank(_claimant);
    _sn.claimFlu(id, _encodedProof());

    assertEq(_token.balanceOf(_claimant), balanceBefore + expectedPayout);

    bytes32 nullifier = keccak256(abi.encodePacked(FluClaimV2Fixture.signals()[2], FluClaimV2Fixture.signals()[3]));
    assertTrue(_verifier.usedNullifiers(nullifier));
    assertEq(_sn.getSafetyNetRequestIds(id).length, 0);
  }

  function test_RealProofRejectedWhenBindingKeyNotRegistered() public {
    uint256 id = _claimReadyNet();

    // Revoke the binding (email-provider) key: the same real proof must now be rejected
    vm.prank(_owner);
    _dkim.revokeDKIMPublicKeyHash(_pubkeyHashB);

    vm.prank(_claimant);
    vm.expectRevert(IZkEmailFluVerifier.InvalidBindingDkimKeyHash.selector);
    _sn.claimFlu(id, _encodedProof());
  }

  function _redeemInvite(uint256 id, address who, uint256 signerKey, uint256 nonce) internal {
    bytes32 typeHash = keccak256('Invite(uint256 safetyNetId,uint256 nonce)');
    bytes32 structHash = keccak256(abi.encode(typeHash, id, nonce));
    bytes32 domainTypeHash = keccak256('EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)');
    bytes32 domainSeparator =
      keccak256(abi.encode(domainTypeHash, keccak256('SafetyNetInvite'), keccak256('1'), block.chainid, address(_sn)));
    bytes32 digest = keccak256(abi.encodePacked('\x19\x01', domainSeparator, structHash));
    (uint8 v, bytes32 r, bytes32 s) = vm.sign(signerKey, digest);
    vm.prank(who);
    _sn.redeemInvite(ISafetyNet.Invite({safetyNetId: id, nonce: nonce}), abi.encodePacked(r, s, v));
  }
}
