// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.28;

import {ProxyAdmin} from '@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol';
import {TransparentUpgradeableProxy} from '@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol';
import {Test} from 'forge-std/Test.sol';

import {DKIMRegistry} from '@zk-email/contracts/DKIMRegistry.sol';

import {SafetyNet} from 'src/contracts/SafetyNet.sol';
import {ZkEmailFluVerifier} from 'src/contracts/ZkEmailFluVerifier.sol';
import {FluClaimGroth16Verifier} from 'src/contracts/verifiers/FluClaimGroth16Verifier.sol';
import {ISafetyNet} from 'src/interfaces/ISafetyNet.sol';
import {IZkEmailFluVerifier} from 'src/interfaces/IZkEmailFluVerifier.sol';

import {FluClaimProofFixture} from 'test/fixtures/FluClaimProofFixture.sol';
import {MockERC20} from 'test/mocks/MockERC20.sol';

/// @dev End-to-end proof of the flu-claim pipeline: a REAL Groth16 proof, generated by the
///      compiled FluClaim circuit over a DKIM-signed fixture email
///      (circuits/scripts/{gen-test-email,gen-inputs,prove}.mjs), verified on-chain through the
///      snarkjs-generated verifier and the full ZkEmailFluVerifier + SafetyNet stack. This is the
///      contract-side validation that the deployed 7-signal layout, the 31-byte claimant packing,
///      and the To:-address Poseidon commitment all agree with the circuit.
///
///      The DKIM key and pubkey-hash below belong to the committed TEST key; never register them
///      on a production DKIMRegistry.
contract FluClaimProofIntegration is Test {
  // poseidonLarge(testKeyModulus, 9, 242) — see circuits/scripts/pubkey-hash.mjs. Equals
  // FluClaimProofFixture.signals()[0], the pubkeyHash the circuit exposed.
  bytes32 internal _testPubkeyHash;

  SafetyNet internal _sn;
  ZkEmailFluVerifier internal _verifier;
  DKIMRegistry internal _dkim;
  MockERC20 internal _token;

  address internal _owner = makeAddr('owner');
  // The claimant is fixed by the proof (its address is bound into the public signals)
  address internal _claimant = FluClaimProofFixture.CLAIMANT;
  address internal _bob = makeAddr('bob');

  function setUp() public {
    _testPubkeyHash = bytes32(FluClaimProofFixture.signals()[0]);

    address impl = address(new SafetyNet());
    address admin = address(new ProxyAdmin(_owner));
    _sn = SafetyNet(address(new TransparentUpgradeableProxy(impl, admin, abi.encodeWithSelector(SafetyNet.initialize.selector, _owner))));

    _dkim = new DKIMRegistry(_owner);
    address groth16 = address(new FluClaimGroth16Verifier());
    _verifier = new ZkEmailFluVerifier(_owner, address(_sn), address(_dkim));

    vm.startPrank(_owner);
    _dkim.setDKIMPublicKeyHash(FluClaimProofFixture.DOMAIN, _testPubkeyHash);
    _verifier.setProvider(FluClaimProofFixture.DOMAIN, groth16, true);
    _sn.setFluClaimVerifier(address(_verifier));
    vm.stopPrank();

    _token = new MockERC20('Mock', 'MOCK');

    // The claimant owns the net so it can sign invites; fund + approve members
    _token.mint(_claimant, 1_000_000 ether);
    _token.mint(_bob, 1_000_000 ether);
    vm.prank(_claimant);
    _token.approve(address(_sn), type(uint256).max);
    vm.prank(_bob);
    _token.approve(address(_sn), type(uint256).max);

    vm.prank(_owner);
    _sn.setTokenAllowed(address(_token), true);
  }

  function _defaultNet() internal view returns (ISafetyNet.SafetyNet memory _cfg) {
    _cfg = ISafetyNet.SafetyNet({
      id: 0,
      owner: _claimant,
      minimumMembers: 2,
      maximumMembers: 5,
      contestThreshold: 33,
      safetyNetStart: 0,
      token: address(_token),
      members: new address[](0),
      initialDeposit: 100 ether,
      fixedDeposit: 10 ether,
      redeemRatio: 1,
      autoThreshold: 50 ether,
      contestWindow: 3 days,
      epochDuration: 30 days,
      smallWithdrawsLimit: 3
    });
  }

  function _encodedProof() internal pure returns (bytes memory) {
    return abi.encode(
      IZkEmailFluVerifier.FluClaimProof({
        domain: FluClaimProofFixture.DOMAIN,
        a: FluClaimProofFixture.a(),
        b: FluClaimProofFixture.b(),
        c: FluClaimProofFixture.c(),
        signals: FluClaimProofFixture.signals()
      })
    );
  }

  function test_RealProofSettlesFluClaim() public {
    // The proof binds the claimant address, and the claimant is not the net owner here, so
    // create a net owned by a keyed helper and invite the claimant in.
    (address keyedOwner, uint256 ownerKey) = makeAddrAndKey('keyedClaimant');
    ISafetyNet.SafetyNet memory cfg = _defaultNet();
    cfg.owner = keyedOwner;
    _token.mint(keyedOwner, 1_000_000 ether);
    vm.prank(keyedOwner);
    _token.approve(address(_sn), type(uint256).max);

    uint256 id = _sn.create('', cfg);

    // keyedOwner signs an invite for the claimant
    _redeemInvite(id, _claimant, ownerKey, 1);

    vm.prank(cfg.owner);
    _sn.start(id);

    // Both members onboard
    vm.prank(keyedOwner);
    _sn.deposit(id, cfg.initialDeposit);
    vm.prank(_claimant);
    _sn.deposit(id, cfg.initialDeposit);

    // Advance past the first epoch (flu waiting period)
    vm.warp(_sn.getSafetyNet(id).safetyNetStart + cfg.epochDuration);

    // The claimant registers the email commitment the proof commits to, then ages it
    vm.prank(_claimant);
    _verifier.registerEmailCommitment(FluClaimProofFixture.EMAIL_COMMITMENT);
    vm.warp(block.timestamp + _verifier.commitmentDelay());

    uint256 balanceBefore = _token.balanceOf(_claimant);
    uint256 expectedPayout =
      (_sn.safetyNetMemberContribute(id, _claimant) * _sn.getEffectiveRedeemRatio(id, _claimant) / 30) * _sn.FLU_PAYOUT_DAYS();

    // Settle the REAL proof: Groth16 verify + DKIM + domain + commitment + nullifier, then payout
    vm.prank(_claimant);
    _sn.claimFlu(id, _encodedProof());

    assertEq(_token.balanceOf(_claimant), balanceBefore + expectedPayout);

    bytes32 nullifier = keccak256(abi.encodePacked(FluClaimProofFixture.signals()[1], FluClaimProofFixture.signals()[2]));
    assertTrue(_verifier.usedNullifiers(nullifier));

    // No request was created — the contest phase was skipped
    assertEq(_sn.getSafetyNetRequestIds(id).length, 0);
  }

  function test_RealProofRejectedWhenDkimKeyNotRegistered() public {
    (address keyedOwner, uint256 ownerKey) = makeAddrAndKey('keyedClaimant2');
    ISafetyNet.SafetyNet memory cfg = _defaultNet();
    cfg.owner = keyedOwner;
    _token.mint(keyedOwner, 1_000_000 ether);
    vm.prank(keyedOwner);
    _token.approve(address(_sn), type(uint256).max);
    uint256 id = _sn.create('', cfg);
    _redeemInvite(id, _claimant, ownerKey, 1);
    vm.prank(cfg.owner);
    _sn.start(id);
    vm.prank(keyedOwner);
    _sn.deposit(id, cfg.initialDeposit);
    vm.prank(_claimant);
    _sn.deposit(id, cfg.initialDeposit);
    vm.warp(_sn.getSafetyNet(id).safetyNetStart + cfg.epochDuration);
    vm.prank(_claimant);
    _verifier.registerEmailCommitment(FluClaimProofFixture.EMAIL_COMMITMENT);
    vm.warp(block.timestamp + _verifier.commitmentDelay());

    // Revoke the DKIM key: the same real proof must now be rejected
    vm.prank(_owner);
    _dkim.revokeDKIMPublicKeyHash(_testPubkeyHash);

    vm.prank(_claimant);
    vm.expectRevert(IZkEmailFluVerifier.InvalidDkimKeyHash.selector);
    _sn.claimFlu(id, _encodedProof());
  }

  function _redeemInvite(uint256 id, address who, uint256 signerKey, uint256 nonce) internal {
    bytes32 typeHash = keccak256('Invite(uint256 safetyNetId,uint256 nonce)');
    bytes32 structHash = keccak256(abi.encode(typeHash, id, nonce));
    bytes32 domainTypeHash = keccak256('EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)');
    bytes32 domainSeparator =
      keccak256(abi.encode(domainTypeHash, keccak256('SafetyNetInvite'), keccak256('1'), block.chainid, address(_sn)));
    bytes32 digest = keccak256(abi.encodePacked('\x19\x01', domainSeparator, structHash));
    (uint8 v, bytes32 r, bytes32 s) = vm.sign(signerKey, digest);
    vm.prank(who);
    _sn.redeemInvite(ISafetyNet.Invite({safetyNetId: id, nonce: nonce}), abi.encodePacked(r, s, v));
  }
}
